### ISSUE TITLE
ModPacker crashes when trying to pack a VM export APK

### ISSUE THREAD

**Issue by lassiterm** [AM2R-Community-Developers/AM2RModPacker#4]
**Describe the bug**
Attempting to create a mod package that includes a VM APK will crash when creating the package. It seems to expect a non-existent AM2R.ini file within the APK.

**To Reproduce**
Attempt to create a mod package with a VM APK.

**Expected behavior**
The ModPacker should create the mod package without crashing due to the VM export's (apparent) lack of an AM2R.ini file.

**Media**
![mod packer settings](https://user-images.githubusercontent.com/8270851/114655443-d57fd080-9cb1-11eb-8359-8abd3682d71a.PNG)
![mod packer apk crash](https://user-images.githubusercontent.com/8270851/114657460-bdaa4b80-9cb5-11eb-9a44-cc21253121ce.png)

**Comment by Lojemiru** [comment]
Incredibly odd that this file doesn't exist on VM, but I'll add a quick check in the copy routine. Should be doing that safely anyway.
