### ISSUE TITLE
ModPacker cannot find path to VM linux files

### ISSUE THREAD

**Issue by lassiterm** [AM2R-Community-Developers/AM2RModPacker#5]
Describe the bug
The ModPacker expects the provided linux zip to have the assets folder and runner in the root of the zip. This appears to be the case with YYC exports, but VM exports appear to have an AM2R folder in the root of the zip which contains the assets folder and runner. Since the expected path does not exist, an error is thrown and the ModPacker does not proceed.

To Reproduce
Make a VM linux export and attempt to create a mod package with it.

Expected behavior
The ModPacker should check for the alternate VM file path, and it should proceed as usual afterwards.

This can be easily fixed by the modder just by moving the assets folder and runner into the root of the linux zip, but a fix would help with ease-of-use and simplicity.

**Comment by Miepee** [comment]
Has been fixed in `feb3638`
